modLoader="javafml"
loaderVersion="[40,)"
license="All rights reserved"

[[mods]]
modId="peculiars" #mandatory
version="${file.jarVersion}" #mandatory
displayName="Peculiars"
logoFile="peculiars.png"
credits="Thanks to Team Abnormals for creating Neapolitan and the MCAbnormals mods."
authors="Uraneptus, EltrutLikes, cosmicgelatin, Catscythe"
description='''Addon for Neapolitan that adds new foods for all of the flavors in MCAbnormals mods (starting with Atmospheric).'''

[[dependencies.peculiars]]
    modId="forge"
    mandatory=true
    versionRange="[40,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.peculiars]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.peculiars]]
    modId="neapolitan"
    mandatory=true
    versionRange="[3.0.0,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.peculiars]]
    modId="blueprint"
    mandatory=true
    versionRange="[5.5.0,)"
    ordering="AFTER"
    side="BOTH"